# Generated by Django 2.0.7 on 2021-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210605_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='output',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
