# Generated by Django 2.0.7 on 2021-06-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memory_limit',
            field=models.FloatField(blank=True, default=268435456),
        ),
        migrations.AddField(
            model_name='post',
            name='time_limit',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
