# Generated by Django 2.0.7 on 2021-06-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210605_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memory_limit',
            field=models.FloatField(default=268435456),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_limit',
            field=models.FloatField(default=1),
        ),
    ]
