# Generated by Django 2.0.7 on 2021-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memory_limit',
            field=models.IntegerField(default=268435456),
        ),
    ]
