version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty1111
  web:
    build: .
    working_dir: /code/app/blogengine/
    command: python manage.py runserver 0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - ./.env.dev
    ports: 
      - 8000:8000
volumes:
  postgres_data:
